Adding Percona XtraDB Cluster
liquibase/liquibase-test-harness pull request #151
Opened 2021-12-13 18:29 UTC by r2liquibase

2021-12-14 21:24 UTC, mcred requested changes

2021-12-14 21:24 UTC, mcred commented on src/test/resources/docker/create-infra.sh
> +  #"edb-9.5"|"edb-9.6"|"edb-10"|"edb-11"|"edb-12"|"edb-13")
Will you clean this up and remove the commented code that's repeated on line 17?

2021-12-15 13:51 UTC, KushnirykOleh commented on src/test/resources/docker/docker-compose.yml
> +      - "./percona-xtradb-cluster-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql"
nit. We may name init file in containers similar to outer files. And now i got why my changes in init file didn't work - i mounted mysql init file instead 🤦‍♂️

2021-12-15 16:17 UTC, r2liquibase commented
OK! @KushnirykOleh, @mcred, and @kristyldatical, we're good! Please merge so I can avoid having to rebase again. Thanks!

2021-12-15 16:19 UTC, kristyldatical approved these changes

2021-12-15 16:20 UTC, KushnirykOleh approved these changes

2021-12-15 16:22 UTC, mcred approved these changes

2021-12-15 16:22 UTC, merged