Added base level test
liquibase/liquibase-test-harness pull request #185
Opened 2022-02-15 11:19 UTC by AlexanderSashchenko

Added a test which checks for basic functionality:
    - Databasechangelog table management
    - Databasechangeloglock table management
    - How the database executes passed strings

2022-02-21 16:10 UTC, KushnirykOleh requested changes
minor change request. But my main concern is that we don't check if Liquibase `rollback`  command works. This was part of ticket requirement per my understanding, and as Snowflake case showed it's worth checking

2022-03-04 11:40 UTC, AlexanderSashchenko commented on src/main/groovy/liquibase/harness/BaseHarnessSuite.groovy
> +@Suite.SuiteClasses([BaseLevelTest, ChangeObjectTests, ChangeDataTests, SnapshotObjectTests])
done

2022-03-04 13:50 UTC, KushnirykOleh requested changes
In current state we only verify how Liquibase works with tracking tables. Need also to ensure update and rollback commands actually worked

2022-03-04 17:14 UTC, nvoxland approved these changes

2022-03-10 15:53 UTC, KushnirykOleh approved these changes

2022-03-10 16:10 UTC, merged