Test fixed sqlite support
liquibase/liquibase-test-harness pull request #217
Opened 2022-04-20 21:52 UTC by nvoxland

## Description

In liquibase/liquibase#2778 I fixed the sqlite snapshot support that was causing these test to fail. I re-enabled them by removing the "INVALID TEST" from the sql files.

The change types don't support update-sql mode which is used for comparing with the expectedSql so those stayed empty.

2022-04-20 21:54 UTC, nvoxland commented
Am I correct that the expectedSql files have to stay empty because those change types don't support update-sql? 

And am I correct that the rest of the tests are still validating that the changes are working correctly even though there isn't an expectedSql file to check?

2022-04-21 08:09 UTC, AlexanderSashchenko approved these changes

2022-04-21 08:19 UTC, AlexanderSashchenko commented
> Am I correct that the expectedSql files have to stay empty because those change types don't support update-sql?
> 
> And am I correct that the rest of the tests are still validating that the changes are working correctly even though there isn't an expectedSql file to check?

Yes, that's right. All the tests are validating for sql identicity but there's a check which catches specific exception: 
if (exception instanceof CommandExecutionException && exception.toString().contains("is not available in SQL output mode"))
In this case I don't fail the test but show info message.

2022-04-21 08:21 UTC, AlexanderSashchenko approved these changes

2022-04-26 13:02 UTC, KushnirykOleh requested changes
addDefaultValueComputed input changelog and expected files (sql and json) need to be overridden as default doesn't work for sqlite. It's because of dropDefaultValue not supported for sqlite. Need to do similar as for other addDefaultValue* for sqlite platform - create separate table in preparation changeset

2022-05-13 15:15 UTC, KushnirykOleh approved these changes

2022-05-13 15:15 UTC, merged