[DAT-10302]Fixed createSequence and dropSequence tests for MariaDb
liquibase/liquibase-test-harness pull request #224
Opened 2022-05-10 14:39 UTC by yodzhubeiskyi

2022-05-10 14:51 UTC, kristyldatical approved these changes

2022-05-13 13:00 UTC, KushnirykOleh requested changes

2022-05-13 13:00 UTC, KushnirykOleh commented on src/main/resources/liquibase/harness/change/changelogs/mariadb/createSequence.xml
> +
plz add comment how and why this changelog is different comparing to default one

2022-05-13 13:00 UTC, KushnirykOleh commented on src/main/resources/liquibase/harness/change/changelogs/mariadb/dropSequence.xml
> +
same here

2022-06-21 13:32 UTC, KushnirykOleh approved these changes

2022-06-21 13:32 UTC, merged