use unique test-harness database name instead of lbcat due to conflicts
liquibase/liquibase-test-harness pull request #330
Opened 2022-08-22 19:16 UTC by jnewton03

2022-08-23 10:09 UTC, KushnirykOleh approved these changes

2022-08-23 10:22 UTC, KushnirykOleh requested changes
then also need to change DB in jdbc connection URL in src/test/resources/harness-config-snowflake.yml
But if someone else uses this config file for connecting to DB it might be screwed again.

2022-08-23 15:30 UTC, jnewton03 commented
> then also need to change DB in jdbc connection URL in src/test/resources/harness-config-snowflake.yml But if someone else uses this config file for connecting to DB it might be screwed again.

@KushnirykOleh I made the change to the harness-config as well:
https://github.com/liquibase/liquibase-test-harness/blob/e63bdf3643e657b6eb086ec7e8afe65d3ecafc96/src/test/resources/harness-config-snowflake.yml#L8

In the future we may want to do something more dynamic, but I think for now this will solve the conflicts.

2022-08-24 13:40 UTC, kristyldatical approved these changes
LGTM. But @KushnirykOleh should also review and remove his change request before merge ideally.

2022-08-25 09:15 UTC, KushnirykOleh approved these changes

2022-08-25 09:16 UTC, merged