DAT-11332 remove terraform code
liquibase/liquibase-test-harness pull request #338
Opened 2022-08-25 17:39 UTC by ap-liquibase

2022-08-25 18:37 UTC, jnewton03 commented
@ap-liquibase You'll also wan to edit the github workflows as part of this PR

2022-08-29 14:14 UTC, jnewton03 requested changes
@ap-liquibase please edit the .github/workflows as well

2022-08-29 16:03 UTC, jnewton03 approved these changes

2022-08-30 13:41 UTC, KushnirykOleh commented on .github/workflows/aws.yml
>      runs-on: ubuntu-18.04
nit - change to ubuntu-latest while we are here

2022-09-02 10:42 UTC, KushnirykOleh approved these changes

2022-09-02 12:30 UTC, merged