Add Snowflake double to float tests.
liquibase/liquibase-test-harness pull request #481
Opened 2023-01-24 12:23 UTC by filipelautert

Add tests to new type DOUBLE specific for Snowkflake

2023-01-24 13:32 UTC, XDelphiGrl approved these changes
This new test goes with Core PR [https://github.com/liquibase/liquibase/pull/3703](https://github.com/liquibase/liquibase/pull/3703). 

APPROVED

2023-01-25 13:13 UTC, KushnirykOleh requested changes
@filipelautert you'll also need to provide expected json file with same name to make it work.
And default workflow doesn't cover Snowflake, so you need to run Snowflake workflow manually for this branch and attach it to PR so it's seen to be working fine

2023-01-25 14:19 UTC, filipelautert commented
> cover Snowflake, so you need to run Snowflake workflow manually for this branch and attach it to PR so it's seen to be working fine

Thanks @KushnirykOleh , json file added!

2023-01-26 17:37 UTC, suryaaki2 approved these changes

2023-02-03 08:58 UTC, KushnirykOleh approved these changes

2023-02-03 08:59 UTC, merged