[DAT-7167] added support for create/rename/drop[sequence]
liquibase/liquibase-test-harness pull request #68
Opened 2021-05-17 15:41 UTC by KushnirykOleh

2021-05-20 14:23 UTC, kristyldatical approved these changes

2021-05-21 11:23 UTC, AlexanderSashchenko requested changes

2021-05-21 11:33 UTC, KushnirykOleh commented on src/main/resources/liquibase/harness/change/changelogs/mssql/createSequence.xml
> +        <rollback>
As for now all our tests don't rely on auto-rollback, so i kept these similar. Let's discuss testing auto-rollback. functionality separately.

2021-05-21 12:25 UTC, AlexanderSashchenko approved these changes

2021-05-21 12:27 UTC, merged