DAT-17032-17033 Setup Azure Postgres 15/16
liquibase/liquibase-test-harness pull request #748
Opened 2024-03-06 08:13 UTC by jandroav

fix(azure.yml): remove 'postgresql:azure' from default databases list… as it is not supported

feat(azure.yml): update job to add support for flexible PostgreSQL server testing
feat(azure.yml): update job to dynamically select PostgreSQL version for testing

2024-03-06 11:52 UTC, PavloTytarchuk requested changes
Hello, @jandroav! [I've tried to run this workflow on GHA](https://github.com/liquibase/liquibase-test-harness/actions/runs/8171448795), and it fails because of this line: 
`url: "${{ secrets['TH_AZURE_POSTGRESQL_FLEXIBLE_SERVER_' + matrix.version + '_URL'] }}"` github doesn't like the '+' symbols.

2024-03-11 08:25 UTC, jandroav commented
@PavloTytarchuk  @jnewton03 Added changes to keep azure postgresql single server version `11` as per this comment: https://datical.atlassian.net/browse/DAT-17033?focusedCommentId=138247

2024-03-11 13:35 UTC, jnewton03 approved these changes

2024-03-12 13:13 UTC, PavloTytarchuk approved these changes
Approved!

2024-03-12 14:51 UTC, merged